sudo: false
dist: trusty
language: node_js
node_js:
- '8'
before_install:
- if [[ `npm -v` != 5* ]]; then npm install --unsafe-perm --verbose -g npm@5; fi
install:
- npm install
script:
- npm run test
notifications:
  email: false
addons:
  sauce_connect:
  	secure: "ISk7bX2PHxtejiK4TGvNBhvAbnvmQ5RhY/AzSvXhRDY1t18vJ1qUZhMB3dxt97pDIFfNWZHhWzh4GOmt0y47bzNTL6Ly5IY5rFch0adwVMuCnFhgwpAW2BmHMZE0EbD6tG4xGjOGhaer2CPSBKO92Nd0VixSzXR71NBCmR8Rmwl3xFa4TD/FSJSXX5kBSp6cJHxtDkrUkF0IBBRiF35SSMkBxIze1ykYqx9wirKH4WqqaEuPAXfIcg+bis55XuPomdmjcmX85PKBOLnDrgjmIRcslqE8nvQZ6qOMaATkLYRoY77nE9JzCktHpJig1+UW0h5ULFVG3RSi/MbfH49I/JRIaO79pcFfBivPrlH9y2oDeFS6Ob/bDW3ZogzpsRHC0Yeb4XZXbDt5lfD8rhdtTaTkzYYPB2QnFC2wvjkNV4UoN4F+SHiJbiqxFSY6uCoyakA7Kw4LIGBDZStB9/xOEkCT0+0EtFpY6lZ3v+VzY8vEp/o+BF1pIKdE/E6gSWX4Gcow/mUSACwtCZzNtqHBbTmlnfKF9W89ZuzJgYOmYBELPpZ8DlYlyN31oRrh3H9SqmjFKlCBuzm3MH56RCLKLwc/33z4v813/gifHm45xk9WrMV1g0KUmZ7d1awe9r33BbOBPvBvXmIhoNAjN4DNUnJNGUdfRKWRyYjiSRSsNrY="
  	secure: "NGIMVuyePHECY167qwtCh2FBA61dmJuVDjvCafNTLVBcAoUqqdfgpYC5MxC/SuCBOqT9iuWCUcqyhFTD8reIZ46Q56Ztf7bUuqrgQ9Mr+aHR6ENWb7Vz0E1vfPzQ1EgP33/JlmzL7EQneWMvox3JK6OTXouwBoJ/QlnDfM8K+QaBXDe5RnRhlZurvYXg5GZ7Gt3U/KkdjJHTVdVo15yyTHAveP0S5YC5DmZpZwUlcevmVlQz0K3pyIsDIJH6IVg6im8E3dLdfk+t+g25BMtTkJHoWFazjuBsMUUTUIy1tKrkK+zoNursfzE6Zmzg5FD2aDtM9Cyc3LzbX8yGFTVa7Bt8u2ko+CuaudnOS78Nmu/ZCZMKU06Gl5EQ86YB8dmgloAuPxXDbNofXsctot6BY2ZjI6jXP61e59tlwrOSpPdCvFR3L/oClHoIGbmgaHE1pjlmS6O6Pr/NUpnMeAkAHojwo+SNhklsOFQNrZbfHMUNilPTaSxwqfSgWrnTVau5RL/JTCyGxDwOHS4nmdA6xlkF5z5uQ2I2zq/bel9vytihewGTpvzj45BF+jOqnpLeTylT4zWKq36v8BFRBNUjYgPifuzBEeVl2FA6g00nk0ZWdTMWPys7NFGtneaB1L8X9BSs2Ol7tEvAlmyeZ5DsdBezfCPE0w3zO4hlb0xmbUI="
